### ISSUE TITLE
Mazda 3 2.0 2021

### ISSUE THREAD

**Issue by lazebnikalan** [Trevelopment/MZD-AIO#105]
wanted to know if this supports the newer version of Mazdas if so how do i go about in installing it?

**Comment by hannad4** [comment]
There are extensive instructions regarding compatibility on https://mazdatweaks.com/

**Comment by Trevelopment** [comment]
This doesn't support the new Mazda infotainment system, just the old one from 2014-2020

**Comment by hansaya** [comment]
Has anyone played around with the newer 2021 models?
