### ISSUE TITLE
Request: Max Volume level on start

### ISSUE THREAD

**Issue by Fhajad** [Trevelopment/MZD-AIO#11]
Any ideas on having a max volume on radio start? It'd be nice for those times after a highway drive you're at a 32 maybe. Then the next day you start up the car, you're not immediately blasted with a 32. It's really nice on my work vehicles where it's a max of 16 on those, so you don't get blasted by someone leaving it loud on accident.

I was going to poke around at it myself to see how to make this happen, but figured I'd try putting it out there if it's one of those "Oh I can do it in 5 min" jobs someone smarter than me can do.

**Comment by Trevelopment** [comment]
Hey I took a look and found how to set the audio volume using JavaScript:
` framework.sendEventToMmui(uiaId, appData, { payload : { audioAutoVolume : level }});`
