### ISSUE TITLE
Unnistall Wifi ap MAZDA

### ISSUE THREAD

**Issue by evr1kaa** [Trevelopment/MZD-AIO#116]
Hello guys, the link  in AIO to script unnistall WIFI AP does not work. please drop a working link to unnistall wifi AP. If you do not have a link, will such a command work "rm -rf /tmp/mnt/data_persist/dev/bin/00-start-wifiAP" for unnistall wifi ap through tweaks.sh

**Comment by Trevelopment** [comment]
link is fixed

**Comment by chengrao2021** [comment]
Hi Trevelopment,
Can you tell me where find the link for unnistall WIFI AP. or send it to me.
Thanks.

**Comment by chengrao2021** [comment]
> Hello guys, the link in AIO to script unnistall WIFI AP does not work. please drop a working link to unnistall wifi AP. If you do not have a link, will such a command work "rm -rf /tmp/mnt/data_persist/dev/bin/00-start-wifiAP" for unnistall wifi ap through tweaks.sh

Hi evr1kaa,
Can you tell me where find the link for unnistall WIFI AP. or send it to me.
Thanks.

**Comment by chengrao2021** [comment]
> link is fixed

Hi Trevelopment,
Can you tell me where find the link for unnistall WIFI AP. or send it to me.
Thanks.
