### ISSUE TITLE
Disable touchscreen all the time

### ISSUE THREAD

**Issue by KhanSW** [Trevelopment/MZD-AIO#118]
The link from the main app to the disable touchscreen all the time results in a 404 error. I need to retrieve this program to re-enable my touchscreen as I am taking it to the shop tomorrow morning to finally get fixed. Can you help me out with a proper link to the program. Thanks!

**Comment by Trevelopment** [comment]
@KhanSW it's probably way too late for this but the link works now http://nots.mazdatweaks.win/

**Comment by lubokkanev** [comment]
The link doesn't work anymore. I found the file in the forum: https://www.mazda3revolution.com/attachments/fully-disable-touchscreen-zip-pdf.283003/

Download and remove the .pdf file extension, then copy to the USB
