### ISSUE TITLE
AIO Won't Run w/ 70.xx.xxx

### ISSUE THREAD

**Issue by Andy-Bob** [Trevelopment/MZD-AIO#123]
2016 Mazda CX-5. Ran program. Selected AIO options. Saved. Compiled. Copied to flash drive.  Inserted flash drive. Entered Accessory Mode.  Nothing happened (actually the radio came on).

![20210622_102721](https://user-images.githubusercontent.com/86360188/123101481-bca24280-d3f9-11eb-81aa-2af660eafb1b.jpg)

**Comment by hannad4** [comment]
![Screenshot_20210623-091214](https://user-images.githubusercontent.com/42780416/123102597-3be84400-d403-11eb-8afb-94cf82b8f816.png)

**Comment by Andy-Bob** [comment]
Good to know.  Are instructions available for this procedure?

**Comment by hannad4** [comment]
all the info you need is on the Mazda tweaks website as far as I am aware

**Comment by Trevelopment** [comment]
Yea all the instructions are here including pictures: https://mazdatweaks.com/serial/ and these are additional instructions: https://mazdatweaks.com/id7/
