### ISSUE TITLE
Reverse camera ( Sorry not an issue just a request )

### ISSUE THREAD

**Issue by simonyangcf** [Trevelopment/MZD-AIO#124]
Dear Developers,

Do you think we can add the option to the tweak, like to turn on reverse camera view whenever we want, or just leave the reverse camera view on for 10seconds after shifting from R to D or R to anything else.

**Comment by umer936** [comment]
I like this. I've been in vehicles where I wish the reverse camera could be on at times when it's not. 
Mercedes does the "leave camera on" after shifting R --> D for ~10 sec. 
Actually my rear windshield is heavily tinted so it would be very beneficial for me at night to just leave it on, so I would definitely use it.

**Comment by Trevelopment** [comment]
Not possible, I tried everything I could to do this and it does not work.
