### ISSUE TITLE
GPS problem 

### ISSUE THREAD

**Issue by PawelSik** [Trevelopment/MZD-AIO#125]
HI All.
I have a problem with GPS when using AA and Google Maps. My positions seems not be exactly where I am. It couses that map/route updates/changes. Sometimes it shows that I'm on different way, in opposite position. 
I checked navi in my phone and it it ok. Custom Mazda Nav is also ok.
Any advice / any gps fix for mazda aa? 

TIA
Pawel

**Comment by Trevelopment** [comment]
Remove your nav SD card when using Android Auto nav
