### ISSUE TITLE
Disabling touch-screen completely

### ISSUE THREAD

**Issue by barcaowl** [Trevelopment/MZD-AIO#127]
If it is possible to enable touchscreen while driving, is it possible to disable it completely. I have the ghost touch issue and I am perfect okay using just the center console and voice commands. Disabling it would be a big big help. I read other comments about the dev not having too much time to continue this, but if it is an easy fix, I would really appreciate it!

**Comment by Trevelopment** [comment]
yea there is, run this tweak http://nots.mazdatweaks.win

**Comment by hadiTab** [comment]
@Trevelopment the link seems to be dead. Is there an alternative link or just a way to get access to this in the app? Thanks.

**Comment by barcaowl** [comment]
> @Trevelopment the link seems to be dead. Is there an alternative link or just a way to get access to this in the app? Thanks.

If you are using CarPlay or android auto with this, it does not work. The ghost touch issue comes back when android auto is enabled and the fix basically doesn't exist. I had to remove my head unit and take off a ribbon cable inside the screen to physically disable the touch screen. It took about 30 minutes, there's videos online.

**Comment by hadiTab** [comment]
Ugh. Was hoping to avoid that. Thanks for the heads up though!

**Comment by lubokkanev** [comment]
Found the tweak in the forums: https://www.mazda3revolution.com/attachments/fully-disable-touchscreen-zip-pdf.283003/
Just remove the .pdf from the file name, after download.
