### ISSUE TITLE
Android Auto Map Not Working W/Mazda CX-5 2017 

### ISSUE THREAD

**Issue by samg80** [Trevelopment/MZD-AIO#13]
Hi there, 
Thank you all for contributing to Android Auto app for Mazda CX series. 
I have a Mazda CX-5 2017. I was successful to download the application and load it to my car. However, when I try to open the Android Auto Map, it shows the message "failed to load plugin '/usr/lib/gstreamer-0.10/libmfw_gst_mpeg2dec.so': lib_mpeg2_dec_arm11_elinux.so.2.2.0: cannot open shared object file: no such file or directory." It freezes on it and at the bottom of that page, it shows" W:/home/mazda/headunit/hu_hu_usb-ccp:446 Start: Nothing found, waiting"
The app doesn't work or launch when I connect my phone through UBS port. 
I have tried to install the app again and again a few times, but unsuccessful. 
I appreciate if you guide me on how to fix this issue. P.S, my phone is Galaxy S9 and the version of the AIO is 2.7.9 

![2018-06-22 17 36 10](https://user-images.githubusercontent.com/40507207/41804573-86bf265c-765e-11e8-8983-07381c456b38.jpg)
![2018-06-22 17 35 55](https://user-images.githubusercontent.com/40507207/41804574-86d77b3a-765e-11e8-9dbe-f3083a95c3b7.jpg)

**Comment by Trevelopment** [comment]
Try some better quality USB cables because you need a high quality cable to make the connection.  Any low - medium quality cable will not allow the phone to completely connect so using a higher quality cable solves this issue 99% of the time.

**Comment by samg80** [comment]
Thank you genius, it solved the issue.

Regards

**Comment by Trevelopment** [comment]
every time
