### ISSUE TITLE
Can we expect that "serial" installation will be changed with "USB" for 59.00.502+ versions in the future?

### ISSUE THREAD

**Issue by kacnje** [Trevelopment/MZD-AIO#130]
I have found MZD-AIO and I'm impressed with its functionality. But unfortunately, my Mazda has version 59.00,502 EU N. 
As a noob, I don't dare to take my headunit out and follow the "serial" instructions. 
Can we expect that in the future we will be able to install AIO via USB? Or is this utopia?

**Comment by Trevelopment** [comment]
nope not possible.  Mazda doesn't want you to be able to modify your system so they try to prevent that with each firmware update.  You are lucky we were able to figure out the serial hack or you wouldn't be able to do anything.
