### ISSUE TITLE
Pause on Mute & Android Auto do not run properly on FW 70.00.000 EU 

### ISSUE THREAD

**Issue by Tristan-cx5** [Trevelopment/MZD-AIO#17]
I installed FW 70.00.000 EU from [this source post in the forum](https://mazda3revolution.com/forums/2014-2018-mazda-3-skyactiv-audio-electronics/98202-mzd-connect-all-firmware-version-only-downloads-290.html#post2399283).
I still have the old USB-Hub, not the new (needed one). 

The pause on mute tweak did not work properly: Pressing mute once playing a mp3 from a USB stick the time continued, but it was silent. Pressing mute the second time, some strange status occured. Exiting and getting back to normal was only possible via commander knob. 

Android Auto from AIO was not possible to start via cable - blackscreen on MZD (needed to reboot) and on the smartphone AA App always restarts in a loop. AA Wifi from AIO was not possible to test, because my test-CMU does have the wifi-bug and can not connect to anything via wifi.

So these two tweaks seem not to be ready for 70.00.000 EU.

Tweaks without a bug in my test: 
- Touchscreen while moving
- Speedometer (Digital Bar)
- No More Disclaimer
- Reverse Camera Safety Warning
- Semi-transparent parking sensor graphic
- Order of Audio Source (FW 70 checkbox was ticked), but neither AA nor CP was visible in the list of audio sources at this 70.00.000 EU

A german Mazda dealer told me today that 70.00.012A EU is the first official FW to download at the moment, so 70.00.000 EU will not be released officially.

**Comment by Trevelopment** [comment]
AA and CP will only show up in the audio sources when you have the new USB hub because the code detects if it is installed to run the instantiating code for AA and CP so they actually are there they are just hidden.  I will check the compatibility of the others they may have changed the code in the mute function just to mess with us.

**Comment by Tristan-cx5** [comment]
Thanks. AHS8 released/linked [here](https://mazda3revolution.com/forums/2014-2018-mazda-3-skyactiv-audio-electronics/98202-mzd-connect-all-firmware-version-only-downloads-295.html#post2399557) to a downloadable 70.00.021A EU (first official EU version) which is the official version for EU. Perhaps you can use this instead of 70.000.000 for testing.

**Comment by Trevelopment** [comment]
Cool dude after a quick comparison there are no concerning changes in regards to AIO compatibility from 70.00.000 - 70.00.021

**Comment by Trevelopment** [comment]
The "Pause on Mute" should work just fine on FW 70 the code that handles that has not changed since before v55.  Are you sure you were testing it with the entertainment screen open?  because it doesn't work if you are outside of the entertainment context.

AA starting up with a black screen is a pretty common problem usually caused by a connected USB drive with lots of music on it or the Nav SD card.  So that one is pretty much expected.

**Comment by Tristan-cx5** [comment]
An hour ago I installed 70.00.021A EU. Afterwards alle Tweaks seemed to be deleted. Pause on mute worked well (mp3 from USB-Stick) before I installed any tweak. Then I installed "my" Tweak-Set again. Most of them worked, but:
- AA 1.09 via cable (from AIO, without Wifi): still black screen, as before; Nav-SD was removed and nothing else connected anywhere (no USB Stick, only the mobile via cable).
- Pause-on-Mute-Tweak: After installation the same problem as described for 70.00.000 occured. After uninstallation of this tweak only Pause-on-Mute worked well again. So I guess they included this function/tweak in the FW 70 and the installation of the AIO tweak is messing it up.
Please see my videos for confirmation:
- [70.00.021A - pause-on-mute-tweak was installed](https://www.dropbox.com/s/sejaptgh9iuq92k/With-pause-on-mute-tweak-installed.mp4?dl=0)
- [70.00.021A - pause-on-mute-tweak was uninstalled](https://www.dropbox.com/s/1ccod6ojd5s7568/Without-pause-on-mute-tweak.mp4?dl=0)
I always/only tested it with the entertainment screen open (track name/picture etc is visible).

**Comment by Tristan-cx5** [comment]
Another user recognized also ([see here](https://mazda3revolution.com/forums/2014-2018-mazda-3-skyactiv-audio-electronics/98202-mzd-connect-all-firmware-version-only-downloads-311.html#post2401495)), that Pause-on-Mute ist included in FW 70. So perhaps it might be worth to include a hint in upcoming AIO version.

**Comment by sahilcc7** [comment]
Getting the black screen issue with AA  1.10+ on V70.00.021. Any solution for this?
