### ISSUE TITLE
Dialog not shown FW v56

### ISSUE THREAD

**Issue by bboybboy** [Trevelopment/MZD-AIO#18]
Hi @Trevelopment 

Got a problem with installation, I formatted flash in FAT32, compile all stuff on MacBook (Used 2.8.0 version) All files were copied into a flash. I turned a car into accessories mode, and plug the flash drive in, wait 10 minutes and nothing happened.

car - Mazda 3 2014, FW v56

**Comment by bboybboy** [comment]
After some googling, I deleted all hidden files on flash. And got only this

![image](https://user-images.githubusercontent.com/3697185/44461369-3a75ec00-a619-11e8-8018-ccb0548cde0d.png)

No any other dialogs...

**Comment by Trevelopment** [comment]
OK, that's good ,that means it is working but did you delete the `tweaks.sh` file too?  You are on a Mac? open up your flash drive after copying the files and start up a terminal in the drive  and type `chmod -R 777 .`  that will change the file permissions if that is the problem then delete all the hidden files.   The fact that you got that dialog means its working but something is wrong with your tweaks.sh file and it cant read it or run it.  You can also try reformatting the drive or try using another USB drive.  But that dialog means it will work fine when you have everything in order.

**Comment by bboybboy** [comment]
Ya, the problem was with a flash drive. I bought a new one and now it's alive. Weird, but Kinston DataTraveler or flash drives with >32Gb won't work properly. 

Many thanks @Trevelopment
