### ISSUE TITLE
Question: List of possible values from vehicle

### ISSUE THREAD

**Issue by davidrus** [Trevelopment/MZD-AIO#2]
Hi, 

just small question. Do someone have list of all possible readable values from car cmu? Something like engine|oil temperature from OBD? 🚗 

I have to plan to develop some application for this infos. 

Thanks

**Comment by davidrus** [comment]
I found some implementation here:
https://github.com/Trevelopment/MZD-AIO/blob/master/app/files/tweaks/config/speedometer/jci/gui/apps/_speedometer/js/speedometer.js#L38

But unfortunately there is no some comment, or docs for it :)..

**Comment by Trevelopment** [comment]
https://github.com/Trevelopment/mazda-custom-application-sdk-simulator/tree/master/src/simulator/data

**Comment by davidrus** [comment]
Thank you @Trevelopment 👍

**Comment by Trevelopment** [comment]
@davidrus this is the shell command to get the values:
```
#smdb-read -n database -e value
# Vehicle Speed
smdb-read -n vdm_vdt_current_data -e VehicleSpeed
```

**Comment by davidrus** [comment]
One more question: Please, do you know if its possible to read engine oil and transmission (automatic) oil temperatures? I tried to find it, but nothing there :(

**Comment by Trevelopment** [comment]
I looked for it and I also did not see it so I think no
