### ISSUE TITLE
AIO 2.8.1 - "No more Beeps" might not work on FW 70

### ISSUE THREAD

**Issue by Tristan-cx5** [Trevelopment/MZD-AIO#24]
Hi Trez,

thanks a lot for AIO 2.8.1.

Yesterday I tested the following tweaks in my CX-5 2016 with FW 70.00.021A-EU (Germany), which are running fine:
- Touch While Moving
- No more Disclaimer
- Reverse Camera Safety Warning
- Semi-transparent parking sensor graphics
- Speedometer - Digital Bar
- Order of Audio Source List (with ticked FW70-checkbox)

During install I got the message that the system is 95% full... perhaps because I had installed the same AIO 2.8.0 tweaks before. The info "95% full" might not really inform, but scares users. They might think - OMG, thats probably bad... What should they do if they read this? How should they react? Concrete information about this 95%-status is missing & might help to calm them down.

Finally - my issue:
Tweak "No More Beep" probably did not work. As I added a radio station to my favorite-list (via star in the radio menu and longpress on the commander knob) the loud beep was still there - even after two MZD-reboots. With earlier firmwares/AIO-versions this tweak worked properly as this beep was not there. Additionally in my MZD settings I always have disabled the beeps, but this beep is not affected by the MZD setting.
Please tell me if I can do some other checks/tests/reports. So far I only know this beep-sound - I do not know where other beeps occus.

Thanks for having a look into this issue.

Cheers
Tristan-cx5

**Comment by Tristan-cx5** [comment]
This is what the AIO_log.log says about the "No More Beeps" tweak - so I guess it is installed:
"INSTALL REMOVE SYSTEM BEEPS ...  *******=============
===                  Modified Beeps in List2Ctrl.js                   ===
========******* END INSTALLATION OF REMOVE SYSTEM BEEPS"

**Comment by Trevelopment** [comment]
Noted on the 95% I have a fix to move backups to the /resources partition when that is encountered for the next release instead of the message which is just suppose to alert you but the install aborts if you run out of space.   As for the no-more-beeps tweak I will look into it and even though I have a copy from the same FW if you could make a JCI backup then send me your `/jci/gui/common/controls/List2/js/List2Ctrl.js`  I will look at it for anything out of the ordinary.  Or you can share the whole JCI backup with me that would be cool too.

**Comment by Trevelopment** [comment]
Also can you show me the file(s) in `/bakups/AIO_log.log` and `bakups/info.log`?

**Comment by Tristan-cx5** [comment]
Thanks for your reply and explanantion & for digging deeper into this issue.

Please find attached the [downloadlink](https://www.magentacloud.de/lnk/KvyUB7cU) for the backup-files: /bakups/AIO_log.log and /bakups/info.log

A full JCI Backup for the no-more-beeps-tweak will follow. Will do it soon.

Info:
Before I had the same tweaks installed on FW 70 with AIO 2.8.0. After installation of the 2.8.1 tweaks I had a never ending spinner after the reboot which is performed after installation. With the spinner running (and the Mazda logo showing) I uninstalled all tweaks with a 2.8.0 unistall-all-rountine (have that usb-stick always in the car). Then I closed the car for > 5 min. (CMU deep sleep) and afterwards it booted fine. Afterwards I reinstalled the 2.8.1 tweaks and everything was fine after the reboot. So I already uninstalled the 2.8.1 tweaks once.

**Comment by Tristan-cx5** [comment]
[Downloadlink](https://www.magentacloud.de/lnk/qoy0hW6A) for my complete JCI backup of FW 70.00.021A EU.

Please keep in mind, that the jci-volans-file and data.zip might be somehow other than you expect it, as it is modified for the speed-cam tweak.

Good luck in finding a solution for the "no-more-beep" issue.

**Comment by Trevelopment** [comment]
Hey do you want to test this for the beeps 
[NO_MORE_BEEPS.zip](https://github.com/Trevelopment/MZD-AIO/files/2534113/NO_MORE_BEEPS.zip)

**Comment by Tristan-cx5** [comment]
Thanks for the possibility to test. Unfortunately your fix freezes the MZD. But it worked fine (added radio station to fav without beep) the one time I could get to test it without a previous freeze.

I tested with different settings: 
1. With my formerly installed tweak-set and speedcam-patch (adapted for FW70 by myself on Diginix patch). 
2. No tweaks, but still installed speedcam-patch.
3. No tweaks at all. Deinstalled also speedcam-patch.
4. Only touch-tweak installed.

At many many tests I only once was able to press the favorite-star-button in the radio/music-screen and it added the radio station to the favorites without any beep. So this seems to work, but the freezes that happened at all the other tests were not there before the installation of the new no-more-beeps-tweak. The system was not usable anymore after the freeze. Pressing the star/fav-button or the music-button aside the commander knob did not lead to any event/nothing happend - even after a reboot, when the selection worked fine (without pressing any menu item). A freeze occured at differnt occasions, no matter if touch or commander knob was used: 
- main screen: selected apps or selected music and pressed it - lead to freeze - had to reboot.
- radio/music menu: seldomly I could enter this menu. pressing one of the bottom menu icons lead to freeze - had to reboot. [screenshot](https://www.dropbox.com/s/2xx89w75djqgbm5/20181102_frozen%20after%20new%20beep%20no%20more.jpg?dl=0)
- reboot screen flickered with white pages since first installation of your new no more beeps tweak - [see video](https://www.dropbox.com/s/s10892stot6v8oe/20181102_flickering%20while%20reboot.mp4?dl=0) from second 10 onwards.

Here you can find the AIO logs/complete usb-stick-contents and a JCI backup:
1. usb content/logs: after first installation of new no more beeps-tweak. I still had some tweaks and speedcam patch installed: [Downloadlink](https://www.dropbox.com/s/0uo8m1ri5ytc8gp/older%20install%20while%20my%20tweaks%20installed.zip?dl=0).
2. usb content/logs: new no more beeps-tweak and touch-tweak was installed only, no speedcam patch: [Downloadlink](https://www.dropbox.com/s/94j2hjn0wsbo2ou/newest%20install%20on%20nearly%20clean.zip?dl=0)
3. JCI backup: new no more beeps-tweak and touch-tweak was installed only, no speedcam patch: [Downloadlink](https://www.dropbox.com/s/t305mr46phqu72l/jci%20backup%20-%20new%20beep%20tweak%20-%20freeze.zip?dl=0)

How can I uninstall your new no more beeps tweak? Could you please provide an uninstall-tweak? Or do I have to use AIO`s FullSystemRestore function (and do the serial method again)? Because now I can not change the radio station or use the MZD at all at the moment... no big deal, as it`s my Test-CMU and not my original one.

**Comment by Tristan-cx5** [comment]
Shall I apply [this fix](https://mazda3revolution.com/forums/2014-2018-mazda-3-skyactiv-audio-electronics/122458-aio-all-one-tweaks-679.html#post2418833) for .100 even if I am on .021A ?

**Comment by Trevelopment** [comment]
Oh man I am so sorry it is a good thing you were the only one that used this installer because I made a little mistake in it.  It only freezes when you try to open a *list view* right? so this will fix that mistake but also full system restore would fix it too if you needed to go that route.  
You don't need that fix but from AIO v2.8.2 on it will be applied to all v70 FW that installs No More Disclaimer or Order of Audio Source just because the extra code is harmless to older FW but required for 70.00.100.
Thanks for testing this for me because I may not have caught that mistake myself and that would have been a real problem if I left it in the release.
[NO_MORE_BEEPS.zip](https://github.com/Trevelopment/MZD-AIO/files/2544807/NO_MORE_BEEPS.zip)

**Comment by Tristan-cx5** [comment]
No worries, glad you found a solution before the release of 2.8.2 ... and yep, the freeze probably was only happening, when entering a list view. Your new tweak/fix from the previous post fixed the freeze. Thanks. Now its working properly. I have added radio stations to the fav list without a beep. Here you can find the [downloadlink](https://www.dropbox.com/s/325p76e9wyaf81a/usb-after-install-of-new-no-more-beeps.zip?dl=0) to the content of the usb stick after the installation. Thanks for the additional info for the other fix. This issue can be closed, as the beep at the adding of radio stations to the fav list will not be there anymore from the no more beeps tweak of AIO 2.8.2 onwards.

**Comment by Trevelopment** [comment]
Awesome done and done
