### ISSUE TITLE
2.8.1 COMPILER NOT WORKING OR TAKING FOREVER

### ISSUE THREAD

**Issue by Stefanuck** [Trevelopment/MZD-AIO#25]
I've updated to the latest AIO version but it does not compile the changes like the 2.8.0 was.  no time out or error message but it keeps running for hours with no result ?

**Comment by ensiform** [comment]
Same issue for me as well. Windows 10 1809 64-bit

**Comment by Trevelopment** [comment]
OK I have a fix coming in the meantime will you tell me the tweaks you are selecting to encounter this so I can make sure my fix is correct for this issue.  Then can you try to select one tweak at a time to see which one is causing the issue. Thanks.

**Comment by ensiform** [comment]
* Backup JCI Folder
* Enable WiFi
* Install SSH_bringback
* Enable Touchscreen While Moving + Fix Cluster Compass
* Remove disclaimer completely
* Install Main Menu Loop
* Install Improved List Loop
* Install Shorter Delay Mod
* Change order of audio sequence list
* Remove automatic message replies
* Install 1 second diagnostic menu
* Install USB audio mod
* Install Bigger Album Art Cover (+Full Width Titles)
* Install Speedometer
* Android Auto v1.10 w/WiFi support
* Install AIO tweaks app (added recently)

**Comment by Trevelopment** [comment]
I found the bug somewhere in the build I have a callback error variable **err** and I try to reference it with **e** so the error throws an error ha

**Comment by Trevelopment** [comment]
OK this is definitely an isolated issue so let's find out what's up.  
- Do you have any special characters or spaces in your username and/or the path to your "AppData" folder? (usually found at C:/Users/{username}/AppData)
- Have you tried compiling the tweaks one at a time to see if any work?  
- Also, could there be some type of permission block on your desktop that is not allowing AIO to create a folder?  For that you can right click the tray icon and change the save location of _copy_to_usb.

**Comment by joshhsoj1902** [comment]
I'm also having the same issue, this is what I'm seeing:

- `C:\Users\jbryans\AppData`
- I tried compiling them one by one when using `2.8.2` and none of them worked. If this is something you would like me to try again let me know.
- I couldn't find the option to change the save location, so instead I tried starting the process as administrator and that didn't help.

![image](https://user-images.githubusercontent.com/4774851/49287108-39e7bf80-f46a-11e8-8449-5ab2334ce2a1.png)

**Comment by ensiform** [comment]
> OK this is definitely an isolated issue so let's find out what's up.
> 
> * Do you have any special characters or spaces in your username and/or the path to your "AppData" folder? (usually found at C:/Users/{username}/AppData)
> * Have you tried compiling the tweaks one at a time to see if any work?
> * Also, could there be some type of permission block on your desktop that is not allowing AIO to create a folder?  For that you can right click the tray icon and change the save location of _copy_to_usb.

I am an US English user so there are no odd characters similar to user above.
Desktop has no permission issues, if it worked in previous version I cannot see why this would have changed.

**Comment by Trevelopment** [comment]
@joshhsoj1902 Can you try just compiling one tweak and see if that works?
