### ISSUE TITLE
Installing AIO Tweaks app changes layout to star layout even without launching app

### ISSUE THREAD

**Issue by marcusds** [Trevelopment/MZD-AIO#27]
Installing AIO Tweaks app changes layout to star layout even without launching app.
Just installing it is enough to change layout to star layout.
Hitting reset tweaks fixes it for now, but on next reboot switches it back to the star layout.

**Comment by Trevelopment** [comment]
That is because it is saved in your localStorage which for some reason doesn't always save and it will go back to its previous state on reboot.

**Comment by marcusds** [comment]
Yes, but I never selected the star layout.

Here is my flow:

Install ASIO Tweaks
Reboot
See star layout without ever launching app
Reset tweaks layout goes back to normal
Reboot
Stars


Why is it setting to stars on first install?

**Comment by Trevelopment** [comment]
So you know how DOM and CSS works right?  So on boot AIO-startup.js reads the localStorage variable "aio.tweaks" and takes that variable and makes that the className of the "body" of the document.  Then attaches a CSS file that uses those classes to change the layout in some way so the star layout is something like 
```
body.star1 .MainMenuCtrlAppHighlight {
    left: 120px;
    top: 40px;
}
```
and so forth then when you press reset tweaks all that does is
```
body.className = "";
```
Therefor I have to say the only conclusion I can make is that your localStorage.getItem("aio.tweaks") = "star1" so you can have you tried CASDK? Part of that framework is the relocation of the save location of localStorage to data_persist which is a better place for saving data.
