### ISSUE TITLE
Wifi doesn't start automatically most of the time, doesnt connect at first attempt

### ISSUE THREAD

**Issue by sayantandas** [Trevelopment/MZD-AIO#28]
Hi,
I own a Mazda 3 2015. 
I installed AIO v2.8.1 recently. I see that after enabling Wifi, it doesn't start at boot most of the time. I have to manually enable it. Also, it doesn't connect to the hotspot at the first attempt. My channel for hotspot is set at 11 as I'm using a Samsung S9+. Still it takes about 3 -4 retries to complete connection.
Any suggestions on how to sort these issues?
Firmware version is 55.x

**Comment by Trevelopment** [comment]
This isn't really an issue with AIO as much as with your CMU's wifi adapter.   I have rarely been able to get wifi to start on boot and for the connection problems they are explained in this issue #19

**Comment by sayantandas** [comment]
Thanks for the answer.
