### ISSUE TITLE
Android Auto not working on Wifi

### ISSUE THREAD

**Issue by sayantandas** [Trevelopment/MZD-AIO#29]
I own a Mazda3 2015 model.
After the initial connect to Android Auto via wifi, subsequent connections have never happened. It never launches AA on the car's Dash Display when connected via Wifi. 
If I connect via cable, AA works well with GMaps. 
I want it to work with wifi .
any suggestions? 
Firmware version is 55.x

**Comment by Trevelopment** [comment]
again #19

**Comment by sayantandas** [comment]
Cool! Thanks!
