### ISSUE TITLE
Video player big mp4 issue

### ISSUE THREAD

**Issue by dolphyvn** [Trevelopment/MZD-AIO#3]
Got memorry errors when trying to play big mp4 file like 400M .

**Comment by Trevelopment** [comment]
Well yea of course you are that is too big of a file to play. You need to make it smaller try converting to H264 video codec AAC audio codec 320p resolution.
You can also use the swapfile but I think that file may be too big even with the swapfile.   If you want to be able to play videos in your car you have to try to make them as small as possible or else its going to be very frustrating for you.

**Comment by Trevelopment** [comment]
Pretty much its like this, the system has less than 1GB of RAM (about a 512 and a 256 = about 750 MB or so)  so a video that is 400 MB is going to take up half of that leaving half for everything else.   I know it doesn't exactly work like that but there is an elementary explanation on why it will not work 90% of the time.
