### ISSUE TITLE
cast screen keeps casting in reverse gear (over rearview)

### ISSUE THREAD

**Issue by aa755** [Trevelopment/MZD-AIO#30]
Is there a way to get the screencast app to temporary pause casting and release the screen for rearview when the car is in reverse gear. If this needed code changes, can someone please point where to start?

**Comment by Trevelopment** [comment]
https://github.com/JonesChi/CastScreen

**Comment by Trevelopment** [comment]
@aa755 would you let me know when you fix this so I can include your fixes in AIO?  Thanks for contributing!

**Comment by aa755** [comment]
I never found time to dig into this and I dont own the car anymore.
