### ISSUE TITLE
Apple Play Available from Mazda

### ISSUE THREAD

**Issue by stevestl** [Trevelopment/MZD-AIO#37]
I'm in the US and received an email offer from Mazda to upgrade my 2016 Miata to include Apple CarPlay for $200 plus labor. Any idea what comes with that? Do you think there will be a MZD-AIO tweak available one day that will provide CarPlay?

Thanks.

**Comment by Trevelopment** [comment]
You get a FW update to v70 and hardware upgrade they replace your USB hub
There will never be a Car Play tweak it is closed source and I don't have an iPhone.
