### ISSUE TITLE
[Feature request]: Display for various gauges

### ISSUE THREAD

**Issue by rkomiyama** [Trevelopment/MZD-AIO#39]
Hey guys, I'm sorry if this feature already exists, but I didn't come across anything like it from what I've read so far.

I'm planning on boosting my ND MX-5 at some point, and I was thinking about whether or not I should install physical gauges, or try to display data on the infotainment screen (similar to this display from the GT-R):

![image](https://user-images.githubusercontent.com/347483/50308053-2aa3d280-0468-11e9-926c-70a21f2b670f.png)

It would show data regarding the boost/vacuum level, fuel pressure, oil pressure, oil temperature, et cetera. How difficult would it be to allow the computer to receive data from various sensors?

**Comment by Trevelopment** [comment]
Did you try the speedometer app?  It shows most of the the available values (oil pressure and temp are not available) if you want to design new visual interface for it be my guest.

**Comment by rkomiyama** [comment]
Sure, but how feasible is it to have the PCM receive data for metrics that don't exist (oil pressure/temp, boost/vacuum level)?

**Comment by Trevelopment** [comment]
Well I don't really know how you would do that.  The way that the data is collected for the speedometer is by reading databases that hold the values.  These are the databases available to the CMU with all the available values in them (take away "casdk-" for the database name): <https://github.com/Trevelopment/mazda-custom-application-sdk-simulator/tree/master/src/simulator/data>.  If you found some other databases or available data points or ways to retrieve that data then I guess it would work but I don't think there are any.

**Comment by TTigges** [comment]
@rkomiyama If you are still interested, I have found a way to integrate external sensor data: https://github.com/TTigges/mzd-usb-sensors (thanks to Mazdaracerdude from mazda3revolution.com). I'm using the data in a modified Speedometer App, but I'm working on an app that shows "additional gauges". You can contact me on instagram @ringspider

**Comment by simonyangcf** [comment]
Did anyone have this theme ? GTR looking gauges on the speedometer app? If yes plssss shareeeee thank you !
