### ISSUE TITLE
AIO 2.8.3 no start

### ISSUE THREAD

**Issue by k3ldon** [Trevelopment/MZD-AIO#41]
Hi!
The installation does not start in FW 70.00.021A 
I think it's because of the changes made to the file tweaks.sh between 2.8.1 and 2.8.3, I've tried at least 6 pendrives.

**Comment by Trevelopment** [comment]
Did you try with just 1 tweak at a time?

**Comment by k3ldon** [comment]
yeap, not load...

Compilation log: https://paste.ubuntu.com/p/yyk6STwpP6/

**Comment by Trevelopment** [comment]
did you try "Build run.sh" option?
also I assumed you already did the serial connection and/or installed autorun and recovery files before this right?

**Comment by k3ldon** [comment]
yeap with recovery, restarting factory, run.sh and alot pendrives 
AIO no start with any pendrive

**Comment by Trevelopment** [comment]
did you try downgrading back to 2.8.1? <https://github.com/Trevelopment/MZD-AIO/releases/tag/v2.8.1>
