### ISSUE TITLE
[INFO] AIO V70

### ISSUE THREAD

**Issue by CokkocZateki** [Trevelopment/MZD-AIO#42]
Hi 

Firstly thank you to everyone involved in these projects. It makes our cars just that little bit more personalized. 

I went to the dealership and got my MZD upgraded with Android Auto. Does AIO work with Version 70?
I dont see anything mentioned in the changelogs so not sure and dont want to bork my Mzd.

Thank you

**Comment by Trevelopment** [comment]
AIO is fully compatible with v70 not all the tweaks are compatible but the ones that are not are skipped when running the installer.  If you did not install the autorun and recovery scripts before you updated then you have to make a [serial connection](https://mazdatweaks.com/serial/) first before you can install tweaks.
