### ISSUE TITLE
Mac OSX - MZD-AIO v284

### ISSUE THREAD

**Issue by cookster1978** [Trevelopment/MZD-AIO#44]
When compiling ready to copy to USB pop-up occurs 
Caught unhandled exception: Cannot read property 'path' of undefined

**Comment by Trevelopment** [comment]
OK so that pops up after you click to copy to USB?  Can you eject the drive and try another USB port maybe?  And make sure its mounted to a letter drive, wait you are using Windows, right?  Just make sure there is a path that is valid to copy to.  Also, what tweaks are you compiling?

**Comment by cookster1978** [comment]
I have tried everything as described. I'm using Mac OSX as software for this platform has become available to download. Only tweak is the Android Auto and removing Disclaimer.

**Comment by Trevelopment** [comment]
Yes but I need more details or else I have no idea what is happening so I don't know how to fix this for you.   So you could shoot me the AIO-compile log or copy and paste the path to your USB drive here so I can see  it or a screenshot or something.  Do you have any special characters ($*/.\:|;`~?!) or spaces in the path?  The error says there is something wrong with the path to your USB drive so lets focus on that, maybe you named it something strange?   Did you try other USB drives?

**Comment by jcspradley** [comment]
I'm getting the same message but I'm not compiling to a USB drive, just the folder. The process gets all the way to the end, then the message pops up and then the app crashes. Below is the last log.

START!
Tweak Files Location: /Users/jcspradley/Desktop/_copy_to_usb
Delete old _copy_to_usb folder...
Wifi added successfully.
Touchscreen Install added successfully.
Speedo Install 1 added successfully.
Speedo-english added successfully.
Speedo-mph added successfully.
Speedo-kml added successfully.
Speedo-temp added successfully.
Speedo_bar added successfully.
Speedo-own_background added successfully.
Speedo-small_speedo_off added successfully.
Speedo Install 2 added successfully.
Copying speedometer files...
Copying androidauto files...
Androidauto Install added successfully.
Copying androidautowifi files...
Androidautowifi Install added successfully.
Copying bin files...
Copying jci files...
59patch added successfully.
Files for androidautowifi copied successfully!
Root files copied successfully!
Files for bin copied successfully!
Files for jci copied successfully!
Files for androidauto copied successfully!
Files for speedometer copied successfully!
End added successfully.
EOL => LF
Writing tweaks.sh

**Comment by Trevelopment** [comment]
Fixed You can try it here: <http://mac.mazdatweaks.win>

**Comment by jcspradley** [comment]
Works perfect, and the new button mapping is amazing! Tremendous thanks for your work.

**Comment by MuyBien** [comment]
Hi!

I recently buy a 2016 CX-3 so I wanted to test your work. Seem's amazing all the stuff that can be done!

But I have the same problem that @jcspradley but on Ubuntu Linux (18.04.2). I have the 2.8.4 version.

Here is my log:

```
# __MZD-AIO-TI__ 2.8.4| MZD All In One Tweaks Installer
#### AIO COMPILATION LOG - Wed May 15 2019 15:06:39 GMT+0200 (heure d’été d’Europe centrale)
___
- *START!*
- Tweak Files Location: /home/fred/Bureau/_copy_to_usb
- Delete old _copy_to_usb folder...
- Sshbringback added successfully.
- Blank Album Art Copy Successful!
- Bgrotator Uninstall  added successfully.
- Copying BackgroundRotator files...
- Touchscreen Install  added successfully.
- Disclaimer Install  added successfully.
- Listloop Install  added successfully.
- Copying list-loop files...
- Audioorder Install  added successfully.
- Pausemute Install  added successfully.
- Msgreplies Install  added successfully.
- Bgart Install  added successfully.
- Copying bigger-album-art files...
- Copying blank-album-art-frame files...
- Copying ssh_bringback files...
- Copying audio_order_AND_no_More_Disclaimer files...
- Blnkframe Install  added successfully.
- Root files copied successfully!
- Copied Preset Messages!
- Files for ssh_bringback copied successfully!
- Files for blank-album-art-frame copied successfully!
- Files for BackgroundRotator copied successfully!
- Files for list-loop copied successfully!
- Files for bigger-album-art copied successfully!
- Files for audio_order_AND_no_More_Disclaimer copied successfully!
- Factory-reset-end added successfully.
- EOL => LF
- Writing tweaks.sh
```

Thanks for any help
