### ISSUE TITLE
AIO 2.8.4

### ISSUE THREAD

**Issue by hwu6712** [Trevelopment/MZD-AIO#45]
recently, I update the AIO to v2.8.4, but the speedmeter can show correctly, all the items show "0", and only idle time which is correct.
Is any one can help what the setting should be or what might be the problem?
Thanks.

**Comment by Trevelopment** [comment]
Swap out the file `/config/speedometer/jci/gui/apps/_speedometer/js/speedometer.js` [with this one](https://raw.githubusercontent.com/Trevelopment/MZD_Speedometer/master/config/jci/gui/apps/_speedometer/js/speedometer.js) (you can `right click > save link as` on that link)

**Comment by hwu6712** [comment]
Got it.
The issue is fixed. MZD  works functionally right now after re-install with your file.
Really appreciate your help!
Thanks a lot.

**Comment by hwu6712** [comment]
Update : two more of my friends have tried and their MZD work functionally as well.
One more question, does it mean the AIO TWEAKS(2.8.4) will update later?
Thanks for your help!

**Comment by Trevelopment** [comment]
I will include the fix in the next version
