### ISSUE TITLE
AIO 2.8.4 playing USB music

### ISSUE THREAD

**Issue by hwu6712** [Trevelopment/MZD-AIO#46]
USB source can't continue playing last time music after next time engine start:
steps to re-produce :
1. listening to usb1 music, turn off the engine.
2. restart the engine, check the audio status.

Usually, the step2 will not show the usb(no connection) and jump to FM.
At least 3 of my friends and me are facing this problem( all of ours are 2018 mazda 6 wagon),
Is there any solution?
Thanks.

**Comment by Trevelopment** [comment]
I haven't heard of this can you tell me what tweaks are installed and FW version?

**Comment by hwu6712** [comment]
AIO tweaks : 2.8.4 (with the speedmeter correction file "speedometer.js" that you provided)
FW : 59.00.545

Thanks.
