### ISSUE TITLE
Android Auto audio lag during animations

### ISSUE THREAD

**Issue by Krogsager** [Trevelopment/MZD-AIO#49]
First off thanks for AIO Tweaks!

Issue:
When driving with Google Maps on the car screen and listening to Google Play Music:
I experience audio lag when the google maps view changes perspective. E.g. when the maps zooms in close to a turn, or rotates at a roundabout, music that is playing choppy.

Setup:
MZD-AIO-TI v2.8.4 - installed Android Auto on my European Mazda3, on FW 56.00
Using android auto 4.1.590944-release
Android 9 phone with USB connected.

Other: I had to do the 180 degrees GPS fix.

**Comment by wikitiki33** [comment]
I can second this issue. Latest MZD-AIO installed on North American 2015 Mazda3 on FW 55.00.760.

Lag is almost never noticeable until I have maps open, then the whole thing stutters and gets a pretty harsh lag.

**Comment by visser** [comment]
Eject the Navigation SD-Card if you have it installed and consider doing the SwapFile Tweak if this persists during high animation sequences within Google Maps.

**Comment by Krogsager** [comment]
Interesting @visser. I checked the [site](https://mazdatweaks.com/).

>The Swapfile will provide your system with an additionasl 1 GB of RAM running from the USB drive for playing videos.

 So if there is a 1GB cap, does it make the most sense to use a small high-speed USB stick and leave it plugged in?

**Comment by visser** [comment]
That's correct, it was intended for the Video Player App where video files would also be on that permanently installed USB stick. 

Run the System Monitor while idling and see how it spikes while music is playing and you zoom in/out with Google Maps then apply the SwapFile tweak and check it again. Let us know how you go :)

**Comment by Krogsager** [comment]
I will do that. Is the system monitor an AIO tweaks feature or standard on the head unit?

**Comment by visser** [comment]
httpa://visser.io/2018/02/toggle-the-system-monitor-cpu-and-memory-overlay-on-the-mazda-connect/

Please mark this issue as resolved mods if you feel this is enough to get it over the line.

**Comment by Krogsager** [comment]
I had trouble reading the system monitor. I expected the graph to go up when utilization of cpu/memory is high (like task manager performance in Windows).

After removing the Navigation SD card the CPU utilization went down, I think. But it did not improve Android Auto performance. 
![IMG_20190401_171627](https://user-images.githubusercontent.com/27994384/55385311-1bcfc000-552d-11e9-804f-377eb365f321.jpg)

Regarding the memory graph, is red the percentage of available memory and the blue the usage?
Performance after boot:
![IMG_20190401_165233](https://user-images.githubusercontent.com/27994384/55385412-62251f00-552d-11e9-9bd7-8d4ec6edf87a.jpg)

Performance after using AA:
![IMG_20190401_165553](https://user-images.githubusercontent.com/27994384/55385518-a57f8d80-552d-11e9-8c80-d9dc1d94b8b7.jpg)

**Comment by iainheng** [comment]
I have reported same problem before without any fix yet https://github.com/gartnera/headunit/issues/143

**Comment by visser** [comment]
Looks like the CPU is maxing out by those photos, I assumed it was a memory limitation responsible; my apologies. I'll keep an eye on the headunit issue on how we can further reduce CPU demand.

**Comment by Krogsager** [comment]
Can I change the layout for a more detailed read-out? E.g. how many megabytes are available.

**Comment by asrikrishnan** [comment]
This is more than just an AIO problem. It is affecting those with other cars including (presumably at least) official versions of AA

https://www.reddit.com/r/GooglePixel/comments/a7kpcu/pixel_3xl_huge_lags_and_audio_stuttering_in/

**Comment by Krogsager** [comment]
Then I will close this issue.
