### ISSUE TITLE
Port for Prius Prime on AGL

### ISSUE THREAD

**Issue by zorrobyte** [Trevelopment/MZD-AIO#51]
Fellow hacker here. I bought a Prius Prime with an 11" touchscreen. It runs AGL.

There's a swath of people who really hate their infotainment system. I'm aware that Toyota likely locked down USB access, etc - but I have a soldering iron and know how to read flash 💃 

I'm hoping that I can get an open console much in the same way you've hacked Mazda's https://mazdatweaks.com/serial/

How did you figure out the RX/TX lines? That'd be an awesome place for me to start.

**Comment by Trevelopment** [comment]
Well someone had already figured that out for me and this guy did a pretty detailed breakdown of the hardware so that helped http://www.2x4logic.com/cmuconnectors.html
