### ISSUE TITLE
Tweak creation creates error on 2.8.4-1 WIN 10

### ISSUE THREAD

**Issue by DanDon** [Trevelopment/MZD-AIO#52]
Program installs and works correctly but when trying to create the copy to usb folder it errors with:
"Caught unhandled exception: cannot read path of 'undefined'"
So can not create any tweaks currently.
Using Windows 10 latest version and tried both 32bit and 64 bit versions of 2.8.4 but cannot find any downloads of previous versions to try out?

**Comment by DanDon** [comment]
Just installed a VM of Windows 7 and the app works fine without the error so it is Windows 10 related

**Comment by Trevelopment** [comment]
Try to reinstall this version on your windows 10 PC https://github.com/Trevelopment/MZD-AIO/releases/tag/v2.8.4
It might be an issue with your connected USB devices, make sure that all connected devices are mounted if you unmount a device and do not disconnect it that is how you get that error

**Comment by hudo** [comment]
I also have this problem under Windows 10 (1903), always stops when writing tweaks.sh
