### ISSUE TITLE
FW 70.00.335 NA: USB tweak install & serial access do not work

### ISSUE THREAD

**Issue by Tristan-cx5** [Trevelopment/MZD-AIO#55]
Hi Trez,

[here](https://mazda3revolution.com/forums/2014-2018-mazda-3-skyactiv-audio-electronics/200450-aio-tweaks-firmware-ver-502-read-105.html#post2447701) a user states, that the new FW 70.00.335 NA (only one *.up-file) does not allow USB Tweak installations (AIO 2.8.4) any more - perhaps they changed something or the ID7 or AIO have to be made .335-compatible. Could you please have a look at that issue, as .335 probably will be soon released for all the other regions too. For NA .335 is already available on the known server.

Thanks & cheers

**Comment by Tristan-cx5** [comment]
Another user identified:

**Comment by Tristan-cx5** [comment]
Serial access with user/jci is also not possible - [see post here](https://mazda3revolution.com/forums/2014-2018-mazda-3-skyactiv-audio-electronics/200450-aio-tweaks-firmware-ver-502-read-106.html#post2447859).

**Comment by mishan** [comment]
That's a bummer.

**Comment by Trevelopment** [comment]
fixed!
