### ISSUE TITLE
mzada 3 2016, pixel 2 XL

### ISSUE THREAD

**Issue by shacharsp** [Trevelopment/MZD-AIO#56]
Hi,
I downloaded the AA on my mazda 3 2016, Im using it with Pixel 2 XL and i have some problems,
Without touching anything its starting to call to my contacts,
The music is stopping too sometimes,
can you help me please,
shachar

**Comment by csirek** [comment]
+1 for the random call happened for me too but only 2 times in the last 2 months. (1.10+ , Oneplus 3T, 56.0.512)

**Comment by Krogsager** [comment]
This sounds more like an AA issue. You might want to take it to the community
https://support.google.com/androidauto/community?hl=en
