### ISSUE TITLE
Speedometer 

### ISSUE THREAD

**Issue by ratte01** [Trevelopment/MZD-AIO#57]
Hi!
I use the version 2.8.4 with my 2015 MX-5 ND and used the speedometer and speed in the statusbar. Now I installed the new speedometer (with the big digital display) and I don't have any GPS information (no, speed, altitude, longitude, latitude) and the rpm. At the attachment you can see the GPS speed is "0" (GPS Geschw) and the rpm is "0" (Motordrehzahl).
I tried the "old" solution to remove and insert the SD-Card, but doesn't work.
![MZD_Version](https://user-images.githubusercontent.com/34778558/58701187-8c1a8680-83a2-11e9-8af0-1c4753057790.jpg)
![MZD_Speedometer](https://user-images.githubusercontent.com/34778558/58701192-8e7ce080-83a2-11e9-8ead-a56eea2e3c98.jpg)

**Comment by Trevelopment** [comment]
That will happen sometimes, did you try a hard reset? (hold nav + back + vol/mute for 20 seconds)

**Comment by ratte01** [comment]
Yes, I did. Nothing changed.
I try now to deinstall it and install it again (with reset between)
Thx

**Comment by ratte01** [comment]
I deinstalled it, reset, installed it again, reset - the same no GPS data

**Comment by sergioafeo** [comment]
Experiencing the same exact issue. Speedometer hasn't worked since installing 2.8.4
