### ISSUE TITLE
No more beeps 2.8.4-1 @ 70.00.335 EU: still beeps @ usb-mp3: fast forward & rewind

### ISSUE THREAD

**Issue by Tristan-cx5** [Trevelopment/MZD-AIO#58]
The "no more beeps" tweak of AIO 2.8.4-1 does not work proberly at FW 70.00.335 EU, as there are still beeps at fast-forward & rewind mp3-music from the usb-stick via longpress of the steering wheel buttons (CX-5 2016).

Adding a new radio favorite does not beep (from factory that beeps) - so the tweak works at least partially.

**Comment by Trevelopment** [comment]
OK so this is something that happens to be outside the scope of the JavaScript GUI environment.  That tweaks disables the beeps by removing the message sent to the MMUI in the function framework.common.beep() but the steering wheel buttons are not handled by JavaScript meaning the beep is handled internally most likely in a binary file.  There may be a way to find where that beep is happening elsewhere in the non-GUI code but it would take some searching and it may not be possible to find without deconstructing some files.

**Comment by Trevelopment** [comment]
@Tristan-cx5 Do this for me: select the prev or next button in the USB audio context and longHold it with the multicontroller to RW or FF.  Let me know if that causes a beep because it shouldn't.

**Comment by Tristan-cx5** [comment]
No, that causes no beep - same if you use the touchscreen instead of the commander knob (pressing the RW/FF buttons). Only when longpressing the steering wheel buttons (RW/FF) the beep occurs.

**Comment by Trevelopment** [comment]
See, it works for the GUI but the steering wheel buttons trigger the beeps directly so they can't be silenced by the No Beeps tweak.  Did you try turning off beeps in the settings?

**Comment by Tristan-cx5** [comment]
Yes, I turned off the beeps in the settings - checked it today and they are still turned off (checkbox is not ticked).
