### ISSUE TITLE
cant view rear camera

### ISSUE THREAD

**Issue by fmyang123** [Trevelopment/MZD-AIO#59]
cant view rear camera when video is playing. it show "black screen" when gear in "R" position while video is playing.

may i know which event/function wll be invoked when rear camera take place?

**Comment by Trevelopment** [comment]
OK I dont understand is the screen black while the car is in drive or in reverse?  Did this happen more than once?  Can you recreate it?
when you shift into reverse the backupparkingApp runs and the visible surface becomes "NATGUI_SURFACE" so video player app will stop playing the video before that happens and resume when it switches back to the app.

**Comment by fmyang123** [comment]
The GUI framework calls noLongerDisplayedFunction callback function whenever it is switching context to another app (in this case, backupparkingApp). The reverse gear is getting blacked out because the app isn't getting killed fast enough?

**Comment by fmyang123** [comment]
intervalVideoPlayer = setInterval(function() {

    if (framework.getCurrentApp() !== '_videoplayer') {
      CloseVideoFrame();
    }
  }, 10); //some performance issues ??

why not centralized this block of codes in noLongerDisplayedFunction?

**Comment by Trevelopment** [comment]
An attempt to kill the video is in the _noLongerDisplayed but that is much too late so it is also attempted to be killed in _StartContextOut and also every 10 milliseconds it checks the context and if the app context is not videoplayer an attempt is made.  So 3 attempts are made so that the video is killed as soon as possible upon exiting the videoplayer app and whichever is successful first will kill the video.

**Comment by fmyang123** [comment]
Hi,may advise me what is the command to go to home screen, is it framework.sendEventToMmui("common", "Global.Home");?Thanks
Sent from Yahoo Mail on Android 
 
  On Wed, 10 Jul 2019 at 4:23 AM, Trezdog44<notifications@github.com> wrote:   
An attempt to kill the video is in the _noLongerDisplayed but that is much too late so it is also attempted to be killed in _StartContextOut and also every 10 milliseconds it checks the context and if the app context is not videoplayer an attempt is made. So 3 attempts are made so that the video is killed as soon as possible upon exiting the videoplayer app and whichever is successful first will kill the video.

**Comment by fmyang123** [comment]
Here you go
https://youtu.be/NOAeKhB2WOw
Is there a way that's able to kill the video before rear camera is launching? Perhaps the above 3 methods is just too late as the camera is already launched

**Comment by fmyang123** [comment]
perhaps some hacks can be done in backupparkingApp.js?

**Comment by fmyang123** [comment]
backupparkingApp.js

backupparkingApp.prototype._BackupCameraDisplayReadyToDisplay = function()
{
// kill video instance?
}

perhaps some hacks can be done in backupparkingApp.js?

**Comment by Trevelopment** [comment]
What FW version are you using?

**Comment by fmyang123** [comment]
59.00.545 4A N

**Comment by Trevelopment** [comment]
Just as thought, that FW version has a black screen issue when exiting AA too that I can't figure out how to fix.  I am guessing it is a similar issue because it is the only FW version where that happens.

**Comment by fmyang123** [comment]
you mean if i upgrade FW to v70.xxx , this issue will be solved?

**Comment by Trevelopment** [comment]
Yes but there is a trade off because you will have to get the upgraded USB hub to run Android Auto but if you don't care about that then yes it will fix that particular issue.

**Comment by fmyang123** [comment]
backupparkingApp.js

//BackupCameraDisplay ctxt
backupparkingApp.prototype._BackupCameraDisplayReadyToDisplay = function()
{
	//modified
	if (framework.getCurrentApp() === '_videoplayer') {
		framework.sendEventToMmui('Common', "SelectApplications"); 
	  }
    //end modified
    this._cachedSpeed = framework.common.getAtSpeedValue();
............
}
i don't have a emulator, so in your opinion if i modify backupparkingApp.js as above to give "way" to reverse camera for FW version 59.00.545 , do you think it's working?

**Comment by Trevelopment** [comment]
So you are sending the MMUI an event to open the applications menu if the current app is videplayer?  I don't really see that that is going to accomplish but try it if you want.  This is the kind of think you can't test in the emulator anyway because the emulator doesn't have a backup camera.

**Comment by fmyang123** [comment]
greetings,
after upgrading my fw to v70, my rootfs is 100% full.
i know that aio tweaks can still be installed with APPS2RESOURCES=1, but i don't like my rootfs to be 100% full.
can you advice me what are the files can be safely deleted to free up some space in roorfs? thanks
