### ISSUE TITLE
Discussion: Stock Android Auto touch screen support on v70+

### ISSUE THREAD

**Issue by issmirnov** [Trevelopment/MZD-AIO#66]
Hey, 

First of all, HUGE thanks for all the time you put into this project. Absolutely stellar work, loved by users all over the world.

I recently installed the tweaks on a v70+ install with stock Android Auto, and discovered the Mazda idiocy with the touchscreen restrictions.

What are your thoughts on the problem? Is there anything I can do to help dive into this? I'm still trying to figure out the layout of the system, so not sure where to start. Could we swap out some APK?

**Comment by mfarreras** [comment]
Hello!

Today I did the serial procedure with also v70 and tried with Android Auto from AIO. Sound doesn't work but touch yes. A minor bug is that home button is on the right.

I'm a computer science engineer and I would love to help, but I need some guidance...

Thanks to the devs that made this possible!

I'm here to help

**Comment by Trevelopment** [comment]
Hi I did a lot of work to try and fix these issues so I can point you in the right direction.  What exactly are you trying to fix first?

**Comment by mfarreras** [comment]
I think the most important thing is the non working sound from AA. The reversed button layout is secondary. What can i try?

**Comment by mellda** [comment]
Fixing the AA for v70 would be really great! Lots of people will be happy. I will keep my fingers crossed.

**Comment by Trevelopment** [comment]
OK maybe you want to start here: https://github.com/gartnera/headunit/blob/master/mazda/callbacks.cpp#L330

**Comment by issmirnov** [comment]
@Trevelopment is this pointer for the sound issue, or my comment about touch on the native AA? I believe @mfarreras is talking about AIO AA, while I am talking about the native Mazda AA. Perhaps it is best to start a separate discussion to avoid mixing the topics.

I'm personally interested in enabling touch on mazda native AA. Do you have some pointers?
