### ISSUE TITLE
Hope can support for "GW3J-31-025.1-M" version

### ISSUE THREAD

**Issue by jlzq1314** [Trevelopment/MZD-AIO#69]
This project is so cool. For MAZDA6 ATEHZA in China, the version is "GW3J-31-025.1-M".  I hope it can be supported too.
Thanks!
![微信图片_20191126221741](https://user-images.githubusercontent.com/10339366/69641329-f6cf2500-109a-11ea-9ce6-1d35f6f18ab8.jpg)

**Comment by Trevelopment** [comment]
nope sorry
