### ISSUE TITLE
Is this compatible with v59.00.504

### ISSUE THREAD

**Issue by cedrickbae** [Trevelopment/MZD-AIO#73]
I know that this is not compatible with 59.00.502+ but on Patrick Lipp website, it says there that 59.00.504 is compatible so I just went straight here if it really is. BTW thank you for this great app.

![image](https://user-images.githubusercontent.com/30261394/75136762-a0689580-5720-11ea-8106-d2531f724acc.png)

**Comment by Trevelopment** [comment]
it is compatible after you make a [serial connection and follow these instructions](https://mazdatweaks.com/serial/)
Also update AIO to [v2.8.5](https://github.com/Trevelopment/MZD-AIO/releases)
