### ISSUE TITLE
Speedometer can't installation 

### ISSUE THREAD

**Issue by cslai83** [Trevelopment/MZD-AIO#75]
![IMG_20200225_225216](https://user-images.githubusercontent.com/61465942/75258533-91b5d780-5821-11ea-98e5-d170b7ed02af.jpg)

**Comment by Trevelopment** [comment]
ok that is strange does it do that every time orf just that one time?

**Comment by Trevelopment** [comment]
did you ever try this again? because it seems like it may have just been a one time thing
