### ISSUE TITLE
Speedometer 6.1: km/h too close to digits

### ISSUE THREAD

**Issue by Tristan-cx5** [Trevelopment/MZD-AIO#76]
With FW 70.00.352 EU and installed Speedometer 6.1 from AIO 2.8.5 I experienced the following minor issue in Speedometer 6.1 digital bar version:

"km/h" is too close to the digits if some three digits are displayed. See photos for details. Perhaps its possible to make "km/h" a smaller font size.

![01_37kmh](https://user-images.githubusercontent.com/34833631/75330813-f1dc6600-5881-11ea-9fcc-5aff275de752.JPG)
![02_149kmh](https://user-images.githubusercontent.com/34833631/75330806-f012a280-5881-11ea-96a0-4f9107720eb0.jpg)
![03_152kmh](https://user-images.githubusercontent.com/34833631/75330809-f143cf80-5881-11ea-8c3a-94c96d42f443.jpg)
![04_151kmh](https://user-images.githubusercontent.com/34833631/75330810-f143cf80-5881-11ea-94c8-0f537b229d00.jpg)
![05_117kmh](https://user-images.githubusercontent.com/34833631/75330812-f1dc6600-5881-11ea-9f8c-e2f218ae45cb.jpg)

**Comment by Trevelopment** [comment]
OK I am going to release v2.8.6 as quickly as I can and I moved this down and to the right a tiny bit and made it a little smaller

**Comment by Tristan-cx5** [comment]
Issue is resolved with AIO 2.8.6:
![Speedometer 6 1 aus AIO 286 _Bild 01](https://user-images.githubusercontent.com/34833631/79015433-fd06ff00-7b6c-11ea-9d70-c03401fb4f2a.JPG)
![Speedometer 6 1 aus AIO 286 _Bild 02](https://user-images.githubusercontent.com/34833631/79015434-fe382c00-7b6c-11ea-8a06-b57a5961b517.JPG)
