### ISSUE TITLE
2.8.5 with no response on 56.00.153 4A N

### ISSUE THREAD

**Issue by matthewdeepblue** [Trevelopment/MZD-AIO#77]
Used MZD-AIO-TI_Setup_2.8.5.exe to make USB disk by guide.

Plugin USB on my CX5 firmwire 56.00.153 4A N and wait for over 20mins, no response on car screen.

**Comment by Trevelopment** [comment]
Did you try multiple USB drives?  
Also you can try on your PC right click the USB drive > Properties > Tools > Error Checking > Check

**Comment by matthewdeepblue** [comment]
> Did you try multiple USB drives?
> Also you can try on your PC right click the USB drive > Properties > Tools > Error Checking > Check

Thanks Trevelopment, I tried another USB, I works well, appreciated with your help !
