### ISSUE TITLE
Andorid Auto doesn't start after updating to 2.8.5

### ISSUE THREAD

**Issue by stefanoceruti** [Trevelopment/MZD-AIO#78]
Hello everyone, 

I updated my Mazda AIO version to the 2.8.5 since the Andorid Auto application (in my car) was crashing after a phone update (different phones).

After the update, the Andorid Auto doesn't start anymore. 
I tried to removes all the Mazda AIO settings and reinstall everything from scratch but it didn't work.

I have a OnePlus 6T but I also tried with a S10 with the same result. I am using the cable and not the WiFi connection. 

Does anyone have the same problem? any idea on how I can resolve it/troubleshoot it?

**Comment by galjun** [comment]
I also have a same problem. Galaxy S8.

**Comment by stefanoceruti** [comment]
This is the error if I try to start the all from AIO Tweaks.

Headunit-wrapper: not found.

Any idea?

**Comment by Trevelopment** [comment]
see #74

**Comment by stefanoceruti** [comment]
Thanks for the reply. I don't have the same error in the installation logs. All looks good to me.

=========================================================================
=======================   START LOGGING TWEAKS...  ======================
======================= AIO v.2.8.5  -  2020.02.02 ======================
================ MAZ_CMU-150_56.00.230A  Flavor cmu150_EU ===============
======================= CMU_SW_VER = 56.00.230A-EU ======================
=======================  COMPATIBILITY_GROUP  = 1 =======================

=======================   MYDIR = /tmp/mnt/sdb1    ======================
==================      DATE = 03/03/20 17:17:38        =================
===         Copytest to sd card successful, mount point is OK         ===
 
=======        Detected compatible version 56.00.230A-EU          =======
 
======***********    BEGIN PRE-INSTALL OPERATIONS ...    **********======
================== Remounted /tmp/mnt/resources =========================
================== Backup of sm.conf.org already there! =================
=====================  Watchdog Already Disabled! =======================
================== Backup of opera.ini already there! ===================
============== Userjs & File Xmlhttprequest Already Enabled =============
======================= data_persist 99% used ===========================
======================== rootfs 82% used ================================
====================== resources 74% used ===============================
================== Over 80% Used Delete Dump Files  =====================
=========************ END PRE-INSTALL OPERATIONS ***************=========
 
==========**************** START ENABLE WIFI ... *************===========
===                       Wifi already active                         ===
===============************* END ENABLE WIFI *************===============
 
=======*************   START INSTALL SSH BRINGBACK   ************========
===      56.00.230A-EU detected, so SSH must already be activated!    ===
======************ END INSTALLATION OF SSH BRINGBACK  ***********========
 
=======******** INSTALL REMOVE TOUCHSCREEN RESTRICTION ... *******=======
===             Touchscreen Speed Restriction Disabled                ===
===               Playing DVDs While Driving Enabled                  ===
====****** END INSTALLATION OF REMOVE TOUCHSCREEN RESTRICTION  ******====
 
========***********    INSTALL NO-MORE-DISCLAIMER ... ***********========
===               Added marker 'systemApp.js.disclaimer'              ===
===      Removed Disclaimer (audio order change was not installed)    ===
=====*********** END INSTALLATION OF NO-MORE-DISCLAIMER ***********======
 
===******* INSTALL REMOVE SAFETY WARNING FROM REVERSE CAMERA ... *****===
===               Reverse Camera Safety Warning Removed               ===
==*** END INSTALLATION OF REMOVE SAFETY WARNING FROM REVERSE CAMERA ***==
 
====****** INSTALL SEMI-TRANSPARENT PARKING SENSOR GRAPHICS ... *****====
===        Copied /jci/nativegui/images/HorizontalSensors/*.png       ===
===         Copied /jci/nativegui/images/VerticalSensors/*.png        ===
===            Copied /jci/nativegui/images/MiniView/*.png            ===
===*** END INSTALLATION OF SEMITRANSPARENT PARKING SENSOR GRAPHICS ***===
 
=====*****************  INSTALL MAIN_MENU_LOOP ... *****************=====
=== Copied /jci/gui/apps/system/controls/MainMenu/js/MainMenuCtrl.js  ===
=======******       END INSTALLATION OF MAIN_MENU_LOOP      ******=======
 
=========************** INSTALL LIST_LOOP_MOD ... *************==========
===                       Copied List2Ctrl.js                         ===
=======************ END INSTALLATION OF LIST_LOOP_MOD ************=======
 
============******** INSTALL SHORTER DELAY MOD ... *********=============
===                  Modified Delay in List2Ctrl.js                   ===
========********* END INSTALLATION OF SHORTER DELAY MOD ********=========
 
============******* INSTALL REMOVE SYSTEM BEEPS ...  *******=============
===     Modified The Beep Method Used By Framework in Common.js       ===
========******* END INSTALLATION OF REMOVE SYSTEM BEEPS  *******=========
 
============**********    INSTALL PAUSE_ON_MUTE ... **********===========
===              Modified /jci/gui/common/js/Common.js                ===
========**********  END INSTALLATION OF PAUSE_ON_MUTE  *********=========
 
==========**************** INSTALL SPEEDOMETER *****************=========
===                 Begin Installation of Speedometer                 ===
===                    Removed Old Speedometer Files                  ===
===                       Copied Speedometer Files                    ===
===                  Copied Speedometer Font Files                    ===
===                  Copied Speedometer Config File                   ===
===                Copied Speedometer controls File                   ===
===                   Copied addon-common folder                      ===
===                 1st line of stage_wifi.sh is OK                   ===
===       Added speedometer entry to /jci/scripts/stage_wifi.sh       ===
===                  Copied additionalApps.js & aio.js                ===
===                   Created additionalApps.json                     ===
===   /tmp/mnt/sdb1/config/bin/node add_app_json.js Speedomete        ===
===                Set Bar Speedometer Color Themes                   ===
===                       Set Fuel Bar Colors                         ===
===              CHANGED SPEEDOMETER TO ENGLISH VERSION               ===
===                         L/100km => km/L                           ===
===               START MODED SPEEDOMETER IN ANALOG MODE              ===
===                SET ORIGINAL SPEEDOMETER BACKGROUND                ===
===              DISABLE SMALL SPEEDOMETER IN STATUSBAR               ===
===               SET STATUSBAR SPEDOMETER MAIN VALUE                 ===
===              SET STATUSBAR SPEDOMETER EXTRA VALUE 1               ===
===              SET STATUSBAR SPEDOMETER EXTRA VALUE 2               ===
===      SET STATUSBAR SPEDOMETER EXTRA VALUE ROTATION INTERVAL       ===
===         HIDE STATUSBAR SPEEDOMETER DURING NOTIFICATIONS           ===
=======**********    END INSTALLATION OF SPEEDOMETER    **********=======
 
=========************   INSTALL AIO TWEAKS APP   *************===========
===                 Removed Old AIO Tweaks App Files                  ===
===                        Copied  aio.js                             ===
===   /tmp/mnt/sdb1/config/bin/node add_app_json.js AIO Tweaks        ===
===           Set Websocketd for AIO in Stage_wifi.sh                 ===
===                  Copied Files For AIO Tweak App                   ===
======********** END INSTALLATION OF AIO TWEAKS APP **************=======
 
=========**************** LOCALSTORAGE TWEAK *****************===========
===                     Created Storage Folder                        ===
===                    Created pstorage folder                        ===
===                    Copied psindex.dat file                        ===
=======************** LOCALSTORAGE TWEAK COMPLETE **************=========

=======************  INSTALL FUEL CONSUMPTION TWEAK ... **********=======
===                   Copied FuelConsumptionCtrl.css                  ===
===                        Copied FuelConsBG.png                      ===
===                    Copied FuelConsumptionCtrl.js                  ===
===                            SET TO KM/L                           ===
===                  Copied js/FuelConsumptionCtrl.js                 ===
========******* END INSTALLATION OF FUEL CONSUMPTION TWEAK ******========
 
====************  INSTALL ANDROID AUTO HEADUNIT APP v1.12...*********====
===                   Removed old Android Auto App                    ===
===      Added Android Auto entry to /jci/scripts/stage_wifi.sh       ===
===                Copied Android Auto Headunit App files             ===
===   /tmp/mnt/sdb1/config/bin/node add_app_json.js Android Au        ===
===                     Android Auto WiFi Support                     ===
====******** END INSTALLATION OF ANDROID AUTO HEADUNIT APP *********=====
 
===*** INSTALL DIAGMENU 1 SEC. CLOCK PRESS IN DISPLAY SETTINGS ... ***===
===              Modified /jci/gui/apps/diag/js/diagApp.js            ===
===                    Modified StatusBarCtrl.js                      ===
===               Modified /jci/gui/common/js/Common.js               ===
===              Added Test Mode (T/M) Button To Diag App             ===
==========********* END INSTALLATION OF 1 SEC DIAGMENU  *********========
 
======================== rootfs 83% used ================================
====================== resources 74% used ===============================
======================= END OF TWEAKS INSTALLATION ======================

**Comment by Trevelopment** [comment]
Just rename this to tweaks.sh, swap it out and run the install again, it will fix your issue: [tweaks.txt](https://github.com/Trevelopment/MZD-AIO/files/4292288/tweaks.txt)

**Comment by stefanoceruti** [comment]
I update the file and now the problem is solved. Thank you!
