### ISSUE TITLE
Reinstall Android Auto Headunit App with Wi-Fi support

### ISSUE THREAD

**Issue by matthewdeepblue** [Trevelopment/MZD-AIO#79]
Hi Trevelopment,

I haven't ticked Wi-Fi support during installation of Android Auto Headunit App,  then I couldn't connect AA by using Wi-Fi.  Is it possible I reinstall Android Auto Headunit App with Wi-Fi support ticked? Do I need to uninstall Android Auto Headunit App first?

Thanks.

**Comment by Trevelopment** [comment]
You can install over it you don't need to uninstall
