### ISSUE TITLE
Force Enable CarPlay on v70.00.21 or later

### ISSUE THREAD

**Issue by chandler767** [Trevelopment/MZD-AIO#80]
There’s a retrofit kit to enable CarPlay and Android Auto on cars 2014 and newer.  

More info: https://9to5mac.com/2018/11/21/mazda-carplay/

The retrofit costs about $450-500 at the dealership or $200 if you buy and install it yourself. The retrofit includes new usb ports, but the retrofit is mostly a firmware update. Unfortunately, the firmware won’t enable CarPlay unless new usb ports are detected.

Is it possible to force enable CarPlay without the usb port install? How could I go about doing this?

**Comment by Trevelopment** [comment]
I'm pretty sure if you could force enable CarPlay it won't work anyway because it needs to use the USB drivers that only work with the upgraded USB ports.
