### ISSUE TITLE
2.8.5 for Mac

### ISSUE THREAD

**Issue by adenot** [Trevelopment/MZD-AIO#82]
Any plans to release 2.8.5 for mac?

**Comment by 84ace** [comment]
#MeToo 
Is there build instructions somewhere? If so, i'm happy to build it.

**Comment by Trevelopment** [comment]
You should be able to build it if you have electron and electron-builder npm packages with `npm run build` but I could not get it to finish the build on my mac for this version

**Comment by Trevelopment** [comment]
[v2.8.6](https://github.com/Trevelopment/MZD-AIO/releases/download/v2.8.6/MZD-AIO-TI-mac_2.8.6.dmg)
