### ISSUE TITLE
Android Auto FW 70.00.335 EU N 

### ISSUE THREAD

**Issue by reddogy** [Trevelopment/MZD-AIO#83]
I use the AA from couple months with some small issue . Last week after connect the phone, the AA doesn't started and I fix the issue with upgrade the app on the phone.
Yesterday,a was planning a trip and want to use Waze and after the address was found, on the route was 0 , shows alternative route, but not starting the process. I was thinking that the issue is also the app, and I restarted the phone. Again nothing. After this I check the settings on the car, and at the system folder where Android Auto was check, I unchecked , thinking that will be possible to check later.
At this moment, the Android Auto and Car play are not possible to be used.
Is not possible to be fixed ?  Definitely I do something wrong and maybe is possible to fixing.
![IMG_20200320_152229](https://user-images.githubusercontent.com/62437472/77182233-1a4c2e80-6ad5-11ea-885e-90aad907233f.jpg)
![IMG_20200320_152214](https://user-images.githubusercontent.com/62437472/77182238-1b7d5b80-6ad5-11ea-9616-f4a673524133.jpg)

**Comment by Trevelopment** [comment]
#36
