### ISSUE TITLE
carOS theme on Linux

### ISSUE THREAD

**Issue by jorgenp** [Trevelopment/MZD-AIO#84]
The carOS theme does not work on Linux since the compile script tries to find ~/.config/MZD-AIO-TI/color-schemes/CarOS/jci.zip. And what is installed by the program there is ~/.config/MZD-AIO-TI/color-schemes/carOS/jci.zip. Since Linux is case-sensitive, it will not work.

Was easily solved by renaming the carOS directory to CarOS, but needs to be fixed in the MZD-AIO-TI.

Version tested was 2.8.5.

**Comment by Trevelopment** [comment]
Thank you for letting me know, will fix for the next version.

**Comment by Trevelopment** [comment]
got it
