### ISSUE TITLE
USB not detected 

### ISSUE THREAD

**Issue by merinjo** [Trevelopment/MZD-AIO#86]
Hey, 

I have a 2017 Mazda 3 with 70.00.100A firmware. I have been trying to install this tweak in my car but my usb does not get detected. I tried different usbs but all have the same effect. 

When I plug in the usb, it does show "'USB NAME' connected" and after that nothing happens. I even tried waiting for some 15-20 minutes still no luck. Tried looking for hidden files in the usb - I am using a windows 10 laptop for running the installer. Windows seems to create a 'System Volume Information' folder each time I plug in the usb but I do make sure I delete it before I disconnect it. Not sure what the issue is, can you tell what can be done to make the usb detectable ?

**Comment by merinjo** [comment]
This is what I see in the log file

`# __MZD-AIO-TI__ 2.8.6| MZD All In One Tweaks Installer
#### AIO COMPILATION LOG - Thu May 07 2020 13:39:08 GMT-0400 (Eastern Daylight Time)
___
- *START!*
- Tweak Files Location: XXXX/_copy_to_usb
- Wifi added successfully.
- Sshbringback added successfully.
- Touchscreen Install  added successfully.
- Videoplayer Install  added successfully.
- Copying videoplayer files...
- Storage Install  added successfully.
- Copying androidauto files...
- Androidauto Install  added successfully.
- Copying ssh_bringback files...
- Copying bin files...
- Copying jci files...
- 59patch added successfully.
- Root files copied successfully!
- Files for bin copied successfully!
- Files for ssh_bringback copied successfully!
- Files for jci copied successfully!
- Files for androidauto copied successfully!
- Files for videoplayer copied successfully!
- End added successfully.
- EOL => LF
- Writing tweaks.sh
- No USB Drives Found- To Install Tweak Files: Copy Entire Contents of "_copy_to_usb" Onto USB Drive.Location: XXXXX- Finished!`

**Comment by Trevelopment** [comment]
Hi @merinjo for your firmware version you have to make a [serial connection](https://mazdatweaks.com/serial/) and install the autorun and recovery scripts to install tweaks. You only have to do that once then you can install tweaks with just a USB drive.
