### ISSUE TITLE
Bluetooth issue

### ISSUE THREAD

**Issue by rahul003** [Trevelopment/MZD-AIO#9]
Does bluetooth work when android auto is not being used? 
Would all the other issues also show up when android auto app is not being used?

**Comment by Trevelopment** [comment]
What issues are you experiencing?  Bluetooth works, I don't know what other issues you are referring to but you should not have any problems with Bluetooth at all.

**Comment by rahul003** [comment]
I haven't installed it yet. I was referring to the bluetooth issue mentioned in the Readme. Maybe that needs to be updated then

**Comment by rahul003** [comment]
Good to know. Thanks :)

**Comment by Trevelopment** [comment]
Oh cool I will update that then because it has been fixed
