### ISSUE TITLE
AIO Tweaks crashes when compiling Autorun & Recovery with WiFi-AP

### ISSUE THREAD

**Issue by andanders** [Trevelopment/MZD-AIO#94]
# Problem
AIO Tweaks v. 2.8.6 crashes with the following message:
> Error Caught unhandled exception

![2020-08-13 15_51_08-MZD-AIO-TI _ MZD All In One Tweaks Installer](https://user-images.githubusercontent.com/49952149/90143139-888fd700-dd7d-11ea-80b1-a2131f698a87.png)

# Expected behavior
AIO Tweaks sould write files to USB drive in XX folder.

# Steps to reproduce
On Windows 10.
- Insert USB Device
- Open Mazda AIO Tweaks
- On main page, click 'Autorun & Recovery'
- Select options as in screenshot
![2020-08-13 15_50_38-MZD-AIO-TI _ MZD All In One Tweaks Installer](https://user-images.githubusercontent.com/49952149/90143499-fb00b700-dd7d-11ea-8ee5-9d0d8e6d04a6.png)

**Comment by veiloctane** [comment]
I too having this issue but if I roll back to v2.8.3 or 2.8.4-1 there is no issue.  

Versions with this issue. 
v2.8.6
v2.8.5


![Uploading 103451196...]


v2.8.3
![image](https://user-images.githubusercontent.com/74845842/103451203-9b3a8680-4cf3-11eb-821a-e6670d443e59.jpeg)

**Comment by fitzroymckay** [comment]
Getting the same exact error on 2.8.6, the file "wifiAP.config" doesn't seem to be created during compilation

**Comment by ryleymcc** [comment]
I am also getting this issue. Is someone looking into this?

**Comment by Trevelopment** [comment]
Yea I am not going to fix this issue, if you really need the wifiAP you can roll back to 2.8.3 or 2.8.4 temporarily
